/*
 * Copyright (C) JasonPercus Systems, Inc - All Rights Reserved
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 *
 * Written by JasonPercus, January 2021
 */
package com.jasonpercus.switchbatteryplugin;

import com.jasonpercus.switchbatteryplugin.network.IPv4;
import java.awt.Color;



/**
 * Cette classe permet de changer l'adresse ip de la prise Shelly Plug S à analyser
 * @author JasonPercus
 * @version 1.0
 */
public class SetIP extends javax.swing.JFrame {
    
    
    
//ATTRIBUT
    /**
     * Correspond à l'icône de l'application
     */
    private final java.awt.Image icon;
    
    /**
     * Correspond au parent de cet objet;
     */
    private final SwitchBattery parent;
    

    
//CONSTRUCTOR
    /**
     * Crée une fenêtre {@link SetIP}
     * @param icon Correspond à l'icône de l'application
     * @param parent Correspond au parent de cet objet;
     */
    public SetIP(java.awt.Image icon, SwitchBattery parent) {
        this.icon   = icon;
        this.parent = parent;
        initComponents();
        this.jip.setIP(new IPv4(this.parent.ip));
        if(this.parent.found){
            this.jip.setForeground(Color.GREEN);
        }else{
            this.jip.setForeground(Color.RED);
        }
    }
    
    
    
//METHODE PUBLIC
    /**
     * Ferme la fenêtre
     */
    @Override
    public void dispose(){
        this.parent.ip = jip.getIP().getIpv4();
        this.parent.saveFileIp();
        super.dispose();
    }
    
    

//METHODE PRIVATE
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jip = new com.jasonpercus.switchbatteryplugin.network.JIP();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set IP");
        setIconImage(this.icon);
        setMinimumSize(new java.awt.Dimension(299, 65));
        setResizable(false);

        jip.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jip, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jip, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jasonpercus.switchbatteryplugin.network.JIP jip;
    // End of variables declaration//GEN-END:variables



}